version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: trend_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: trend_stream  # 여기서 DB를 미리 만들어줍니다!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # 2. Zookeeper (Kafka 관리자)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: trend_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 3. Kafka (메시지 큐)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: trend_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 4. Kafka UI (눈으로 보는 관리 도구)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: trend_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

volumes:
  mysql_data: